pool:
  vmImage: windows-latest
  demands: Cmd

trigger:
  branches:
    include:
      - refs/tags/*

pr: none

variables:
  - group: signingSecrets #create this group with SECRET variables `signingUsername` and `signingPassword`
  - group: nugetKeys #create this group with SECRET variables `nugetKey`
  - name: githubConnectionName
    value: AkkaDotNet_Releases
  - name: projectName
    value: Akka.Persistence.Sql
  - name: githubRepositoryName
    value: akkadotnet/Akka.Persistence.Sql
  - name: buildConfiguration
    value: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET'
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- powershell: |
    .\build.ps1
  displayName: 'Update Release Notes'
  continueOnError: false

- powershell: |
    dotnet pack --configuration $(buildConfiguration) --include-symbols --verbosity normal --output .\bin\nuget 
  displayName: NuGet Pack
  continueOnError: false

# PowerShell script to push all NuGet packages to NuGet.org
- powershell: |
    $ErrorActionPreference = "Stop"  # Makes the script stop on errors
    Get-ChildItem "bin\nuget\*.nupkg" -Recurse | ForEach-Object {
      dotnet nuget push $_.FullName --api-key $(nugetKey) --source https://api.nuget.org/v3/index.json
    }
  displayName: 'Push to NuGet.org'
  continueOnError: false

- task: GitHubRelease@0
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: $(githubConnectionName)
    repositoryName: $(githubRepositoryName)
    title: '$(projectName) v$(Build.SourceBranchName)'
    releaseNotesFile: 'RELEASE_NOTES.md'
    assets: |
      .\bin\nuget\*.nupkg
