pool:
  vmImage: windows-latest
  demands: Cmd

trigger:
  branches:
    include:
      - refs/tags/*

pr: none

variables:
  - group: signingSecrets #create this group with SECRET variables `signingUsername` and `signingPassword`
  - group: nugetKeys #create this group with SECRET variables `nugetKey`
  - name: githubConnectionName
    value: AkkaDotNet_Releases
  - name: projectName
    value: Akka.Persistence.Sql
  - name: githubRepositoryName
    value: akkadotnet/Akka.Persistence.Sql

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 8'
  inputs:
    version: '8.x'

- task: BatchScript@1
  displayName: 'Update Release Notes'
  inputs:
    filename: build.ps1
  continueOnError: false

- task: DotNetCoreCLI@2
  displayName: NuGet Pack
  inputs:
    command: 'pack'
    configuration: 'release'
    includeSymbols: true
    packDirectory: .\output
  continueOnError: false

- task: DotNetCoreCLI@2
  displayName: NuGet Push
  inputs:
    command: 'push'
    nugetFeedType: 'external'
    externalEndPoint: 'https://api.nuget.org/v3/index.json'
    publishFeedCredentials: $(nugetKey)
    packagesToPush: .\output\*.nupkg
  continueOnError: false

- task: GitHubRelease@0
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: $(githubConnectionName)
    repositoryName: $(githubRepositoryName)
    title: '$(projectName) v$(Build.SourceBranchName)'
    releaseNotesFile: 'RELEASE_NOTES.md'
    assets: |
      .\output\*.nupkg
